name: agripharm
description: A new Flutter project.
publish_to: "none" #
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chat_gpt_sdk: 2.0.2
  speech_to_text: ^6.1.1
  page_view_dot_indicator: ^2.1.0
  file_picker: ^4.6.1
  image: ^3.2.2
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.7+5
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  image_cropper: ^4.0.1
  cloud_firestore: ^4.8.0
  tflite_flutter: ^0.9.0
  logger: ^1.4.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  fluttertoast: ^8.1.1
  url_launcher: ^6.1.5
  cached_network_image: ^3.0.0
  intl: any
  flutter_localizations:
    sdk: flutter
  pinput: ^2.2.16
  get: ^4.6.5
  flutter_riverpod: ^2.3.6
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  barcode_widget: ^2.0.3
  flutter_qr_bar_scanner: ^3.0.2
  http: ^0.13.5
  flutter_barcode_scanner: ^2.0.0
  build_runner: any
  freezed: ^2.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
